### ISSUE TITLE
Bug: notification for highlight created redirects to the feed instead of the created highlight

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/app#1575]
### Describe the bug

When you click a highlight created notification, it visits `/feed/undefined` and then redirects you to `/feed`

![notif-bug](https://github.com/open-sauced/insights/assets/79809121/17dd5297-3e1b-40b2-986d-b8c0b4a01a3a)

For some reason the highlight `meta_id` is undefined. This is most likely a backend bug.

![notif-metaid-bug](https://github.com/open-sauced/insights/assets/79809121/ee150d29-e48e-433a-8581-2f3eb0f0f34f)

Any ideas @brandonroberts?

### Steps to reproduce

1. Go to your notifications
2. If you follow a user that has created a highlight, you will see the notification and when you click on it, it redirects you th the feed page

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
I believe this is resolved in the API already, and will go out with the next release soon

**Comment by jpmcb** [comment]
Hmmm, I'm still seeing this on prod right now with this latest release that just dropped: https://github.com/open-sauced/app/releases/tag/v1.61.0

<img width="1512" alt="Screenshot 2023-08-25 at 1 46 06 PM" src="https://github.com/open-sauced/app/assets/23109390/46f0f071-1816-4937-b30c-adb073f61747">

And using a raw request, it doesn't look like it's fixed on the API

```sh
curl -X 'GET' \
  'https://api.opensauced.pizza/v1/user/notifications?page=1&limit=10&range=30' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <redacted>'

{
  "data": [
    {
      "id": 7613,
      "user_id": 23109390,
      "from_user_id": 42211,
      "type": "highlight_created",
      "message": "brandonroberts created a new highlight",
      "notified_at": "2023-08-25T15:13:59.428Z",
      "read_at": "2023-08-25T19:38:52.086Z",
      "meta_id": "undefined",
      "from_user": {
        "id": 42211,
        "open_issues": 83,
        "created_at": "2008-12-23T02:43:29.000Z",
        "updated_at": "2023-08-25T11:01:05.641Z",
        "first_opened_pr_at": "2012-10-06T02:35:52.000Z",
        "first_pushed_commit_at": "2013-01-22T06:22:13.000Z",
        "connected_at": null,
        "node_id": "MDQ6VXNlcjQyMjEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/42211?u=32763fc85100fa45c5aa5d4bdddc4344e53d0173&v=4",
        "gravatar_id": "",
        "url": "https://github.com/brandonroberts",
        "login": "brandonroberts",
        "is_private": false,
        "is_open_sauced_member": true,
        "is_onboarded": true,
        "is_waitlisted": false,
        "role": 50,
        "bio": "Web developer, @ngrx  maintainer, creator of @analogjs, GDE, sports ranter, and gif slinger. Head of Engineering @open-sauced .",
        "blog": "https://brandonroberts.dev",
        "name": "Brandon Roberts",
        "twitter_username": "brandontroberts",
        "linkedin_url": "https://www.linkedin.com/in/brandontroberts",
        "github_sponsors_url": "https://github.com/sponsors/brandonroberts",
        "discord_url": "",
        "company": "CodeSequence, LLC",
        "location": "Alabama",
        "display_local_time": false,
        "interests": "typescript,javascript",
        "hireable": false,
        "public_repos": 257,
        "public_gists": 69,
        "type": "User",
        "display_email": false,
        "receive_collaboration": true,
        "timezone": "Central Standard Time",
        "languages": {
          "CSS": 9860,
          "HTML": 3406,
          "JavaScript": 727,
          "TypeScript": 56183
        }
      }
    },
    // etc ...
  ],
  "meta": {
    "page": 1,
    "limit": 10,
    "itemCount": 25,
    "pageCount": 3,
    "hasPreviousPage": false,
    "hasNextPage": true
  }
}
```

---

Should we move this issue to the API repo?

**Comment by brandonroberts** [comment]
That's fine. It's a TypeORM issue. The fix is to use the `@PrimaryGeneratedColumn` instead of `@PrimaryColumn` on the id to tell it to return the ID back after inserting.

**Comment by takanome-dev** [comment]
Sending a pr for this in the API
