### ISSUE TITLE
feat: Public workspaces don't have a path auth when creating a workspace

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2812]
## Situation

I was testing the public workspace for OpenSauced to see what the experience was like if a repository insight was shared. 

https://app.opensauced.pizza/workspaces/1b814876-2007-4125-91bf-9792b93ee6d2/repositories

![Screen Shot 2024-02-28 at 3 49 06 PM](https://github.com/open-sauced/app/assets/5713670/137e02bc-3b53-496c-ad7a-f162f2aa4a9e)

## Problem 

When I click "create a workspace" I'd expect to be asked to log in. 

![Screen Shot 2024-02-28 at 3 49 09 PM](https://github.com/open-sauced/app/assets/5713670/792b35a1-a021-456b-a5fd-d21316bb43eb)

## Solution

Add an auth redirect that takes the user to log in and return to the creation flow. 

## Additional info
Also [pizza.new](https://pizza.new) is broken because of this.

**Comment by nickytonline** [comment]
It 404s at the moment because they're not logged in. It's a 401 really but we pretend like the page is not found like GitHub does for stuff you don't have access to.

The Create workspace link is supposed to be removed when logged out. It didn't make it into the MVP. If we want to keep it, we can redirect to the login.

**Comment by bdougie** [comment]
We can do either, but I lean toward some action encourages the not logged in user is recommended to log in. 

Maybe that is replacing the drop down with sign up to do X

**Comment by nickytonline** [comment]
I think the redirect to login makes sense. Thoughts @brandonroberts @isabensusan?

**Comment by brandonroberts** [comment]
Redirect works for me. It does bring up the question of whether we want to automatically send people to the GitHub login modal, or back to the feed to login, and redirect them back to the previous page

**Comment by brandonroberts** [comment]
Or perhaps a dedicated login page with the GitHub login

**Comment by nickytonline** [comment]
A dedicated login page would make sense.

**Comment by isabensusan** [comment]
Let's not hide the "Create a new workspace" cta for non-logged in users. 

Here's a couple low/mid-effort ways I can think of to tackle this:
A - [lowest effort] When the non-logged in user hovers over the "create new workspace" button, we show a tooltip saying "You need to log in to create a new workspace" --> on click we redirect to the Github Login
B - If a non-logged in user clicks on the "create new workspace" button, we trigger a "Login" saying that they need to login to create a workspace, and show the "Connect with GitHub" CTA --> on click we redirect to the Github Login (that way we avoid creating a dedicated login page for now, which isn't super high priority atm).

B would be preferred, but I know modals can be trickier than they seem @nickytonline . We can always come back and create a dedicated login page in the mid term, but ideally we fix this quicker with one of these two solutions.

@brandonroberts @bdougie  @nickytonline  any thoughts?

**Comment by bdougie** [comment]
I lean towards B. Shortcuts tend to be permanent solutions.

Perhaps this is A as a PR 1 and then B as a follow up PR?

**Comment by brandonroberts** [comment]
Option B sounds good to me. We have some examples for modals already

**Comment by bdougie** [comment]
Bumping this. 

I preparing a demo for a team and realize this will be a little awkward with me manually adding them, but that would require them connecting their GitHub first. 

Note: this is a large enterprise and chances that happening is low.

**Comment by nickytonline** [comment]
@brandonroberts is at a conference so I can take this as high priority. When is the demo?

**Comment by brandonroberts** [comment]
So we want the "Create New" buttons to make them connect their GitHub?

**Comment by isabensusan** [comment]
## Suggested Solution

Here's an approach we could take for now (as described in the mock): 

1. Show a pill next to the workspace name in the header that says "public"
2. Add the copy: “Sign up to get your own workspace” to the login button in the navbar
3. Remove the dropdown, instead replace it with the name of the workspace (and the orange square, to add a pop of color)

And as an extra:
4. Add a card in the sidebar to entice users to create their own workspace with a CTA to connect their github account, and with a "Learn More" link to workspaces documentation ([link to use](https://docs.opensauced.pizza/features/workspaces/))

<img width="1507" alt="image" src="https://github.com/open-sauced/app/assets/27322879/a46ce6ee-d648-4939-9eb5-9a9eb626a6e0">

## Non suggested approach
We could also add a toast, but because we are already showing the "introduction to workspaces" modal, I don't want to add more pop ups that could get too annoying. Adding an option to create your own workspace within the "introduction to workspaces" modal isn't an option either, because people won't know what a workspace even is yet.

**Comment by nickytonline** [comment]
> ## Suggested Solution
> Here's an approach we could take for now (as described in the mock):
> 
> 1. Show a pill next to the workspace name in the header that says "public"
> 2. Add the copy: “Sign up to get your own workspace” to the login button in the navbar
> 3. Remove the dropdown, instead replace it with the name of the workspace (and the orange square, to add a pop of color)
> 
> And as an extra: 4. Add a card in the sidebar to entice users to create their own workspace with a CTA to connect their github account, and with a "Learn More" link to workspaces documentation ([link to use](https://docs.opensauced.pizza/features/workspaces/))
> 
> <img alt="image" width="1507" src="https://private-user-images.githubusercontent.com/27322879/314193698-a46ce6ee-d648-4939-9eb5-9a9eb626a6e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzkwNzYsIm5iZiI6MTcxMDkzODc3NiwicGF0aCI6Ii8yNzMyMjg3OS8zMTQxOTM2OTgtYTQ2Y2U2ZWUtZDY0OC00OTM5LTllYjUtOWE5ZWI2MjZhNmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEyNDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMDI5Y2Y4NTgxOTVmNmVkMWM4NmIyMzg2NzNkNDk0ZjM3NDc4NTFjNjFiZGY5ODlhZDAzODNkNjQzN2ZlODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5AXqe_2zXNFCODDonI6JMYsaYbKRs5iXzEcjH8g4iU">
> ## Non suggested approach
> We could also add a toast, but because we are already showing the "introduction to workspaces" modal, I don't want to add more pop ups that could get too annoying. Adding an option to create your own workspace within the "introduction to workspaces" modal isn't an option either, because people won't know what a workspace even is yet.

I like the CTA for connecting GH in the sidebar, but probably for large screens only. There wouldn't be much realestate on a phone in the sidebar for it.

For the Public pill, I'm going to create a separate issue for that as that's a nice addition in general outside of this feature.

**Comment by isabensusan** [comment]
I wonder if on mobile we can create a bottom banner to entice users to sign up so we don't lose that opportunity?

**Comment by brandonroberts** [comment]
Part of this is resolved by https://github.com/open-sauced/app/pull/2935 where you can start the creation of a new workspace without being logged in, connect your account, and finish completing it.

https://github.com/open-sauced/app/pull/2935

**Comment by BekahHW** [comment]
Is this resolved or do we want to do more work here? When I checked in the incognito window, I can start to create, but the only buttons I can use are connect with GH? This is better than a 404, but is also a little confusing. It feels like you're missing a button.


<img width="1500" alt="image" src="https://github.com/open-sauced/app/assets/34313413/3da481a1-03ad-4f5f-af84-a473f08797e6">

**Comment by bdougie** [comment]
This is not resolved. The user is still presented with a blank dropdown. Adding context to the sidebar should be a follow up to #3259

https://github.com/open-sauced/app/issues/2812#issuecomment-2007917285

**Comment by bdougie** [comment]
Related https://github.com/open-sauced/app/issues/3377

**Comment by bdougie** [comment]
> Is this resolved or do we want to do more work here? When I checked in the incognito window, I can start to create, but the only buttons I can use are connect with GH? This is better than a 404, but is also a little confusing. It feels like you're missing a button.

The problem is fixed now you can open the workspace creation flow. I don't think there is enough for the user to have context  on why they would create a workspace. 

I'd love for us to scope this design @isabensusan did to prompt the user to "get their own workspace"

![image](https://github.com/open-sauced/app/assets/5713670/e5f69c70-6065-41d3-b6c0-2087720477fe)

This already exist on mobile

<img width="291" alt="Screenshot 2024-05-15 at 6 48 13 AM" src="https://github.com/open-sauced/app/assets/5713670/ca3e2f04-f44c-4f91-a6e2-0d7c82003e5a">
